from pathlib import Path
import argparse,json,sys,numpy as np,pandas as pd
ROOT=Path(__file__).resolve().parents[1]; sys.path.insert(0,str(ROOT/"src"))
from msdp.calibration import StaticCQRCalibrator
from msdp.inference import predict_latest
p=argparse.ArgumentParser(); p.add_argument("--config"); p.add_argument("--data",required=True); p.add_argument("--model",required=True); a=p.parse_args(); row,out,bundle=predict_latest(a.data,a.model,ROOT/"artifacts/scalers/feature_scaler.joblib"); cal=StaticCQRCalibrator.from_state_dict(bundle["conformal"]); payload={"data_date":str(row.date),"current_vnindex":float(row.close),"note":"Hồ sơ dự báo theo khoảng thời gian; không phải đường giá tương lai","horizons":[]}; hs=bundle["config"]["horizons"]
for j,h in enumerate(hs):
    lo,hi=cal.transform(np.array([out["return_quantiles"][j,0]]),np.array([out["return_quantiles"][j,-1]])); q=out["return_quantiles"][j]; payload["horizons"].append({"horizon":h,"probability_positive":float(out["direction_prob"][j]),"return_quantiles":q.tolist(),"raw_interval":[float(q[0]),float(q[-1])],"calibrated_interval":[float(lo[0]),float(hi[0])],"projected_index_quantiles":[float(row.close*np.exp(q[x]/100)) for x in [0,2,4]],"projected_calibrated_interval":[float(row.close*np.exp(lo[0]/100)),float(row.close*np.exp(hi[0]/100))],"mdd_quantiles":out["mdd_quantiles"][j].tolist(),"volatility":float(out["volatility"][j]),"expert_weights":out["gate_weights"][j].tolist(),"normalized_gate_entropy":float(-(out["gate_weights"][j]*np.log(np.clip(out["gate_weights"][j],1e-9,None))).sum()/np.log(len(out["gate_weights"][j]))),"expert_disagreement":float(out["expert_disagreement"][j])})
target=ROOT/"artifacts/predictions"; (target/"latest_forecast.json").write_text(json.dumps(payload,indent=2),encoding="utf-8"); pd.json_normalize(payload["horizons"]).to_csv(target/"latest_forecast.csv",index=False); md="# Hồ sơ dự báo theo khoảng thời gian mới nhất\n\n```json\n"+json.dumps(payload,indent=2)+"\n```\n"; (target/"latest_forecast.md").write_text(md,encoding="utf-8"); (target/"latest_forecast_VI.md").write_text(md,encoding="utf-8"); print(json.dumps(payload,indent=2))
